# https://github.com/apps/auto-me-bot
---
pr:
  autoApprove:
    users: ['dependabot', 'allcontributors']
  conventionalTitle:
    rules:
      'body-max-line-length': [2, 'always', 120]
  lifecycleLabels:
    ignoreDrafts: true
    labels:
      reviewRequired: "status: needs review"
      changesRequested: "status: changes requested"
      moreReviewsRequired: "status: needs more reviews"
      reviewStarted: "status: review started"
      approved: "status: approved"
      merged: "status: merged"
  tasksList:
