---
name: Pull request build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and verify skill handler
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3.9.0
        with:
          distribution: adopt
          java-version: 11
          cache: maven

      - name: Verify and create coverage reports
        working-directory: ./lambda
        run: mvn verify -Pits,cov -B -ff

      - name: Upload integration test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: it-logs
          path: lambda/target/it/shabbat-times-interaction-it/build.log
          if-no-files-found: warn

      - name: Report test summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          test_changes_limit: 0
          files: ./lambda/target/junit-platform/TEST-junit-jupiter.xml
          report_individual_runs: true

      - name: Push coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./lambda/target/site/jacoco/jacoco.xml
