---
name: Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Java 11
        uses: actions/setup-java@v2.3.0
        with:
          distribution: adopt
          java-version: 11
          cache: maven

      - name: Test and create coverage reports
        working-directory: ./lambda
        run: mvn test jacoco:report -B -ff

      - name: Push to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: lambda/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
